### ISSUE TITLE
free - nonfree split

### ISSUE THREAD

**Issue by norbusan** [texjporg/jfontmaps#1]
現在のjfontmapsでは、だいたいcommercial fontのサポートしています。TeX Live側から望まれてることがあります：commercial/freeの分けること。
一つの提案は：jfontsmapsとjfontmaps-nonfreeを作って、jfontmapsでipa(ex)のサポートだけに入って、TeX Liveの中に配って、jfontmaps-extraをtltexjpから配ること。

jfontmapsのリポシトリの新しいbranch「split-nonfree」を作成しました。

どう思いますか。

**Comment by kmaed** [comment]
私は Linux ユーザなので困りませんが，特に Mac のユーザはヒラギノが標準で埋め込めなくなると困惑するのではないかと思います．commercial/free を分離すべきだという考え方はある程度理解できますが，フォローする体制を整えないと質問が多発しそうです．

**Comment by norbusan** [comment]
そうですよね。。。基本的にヒラギノ等を使いたい方はいっかいtltexjpからjfontmaps-nonfreeをインストルしないといけません。これは大きい問題になるかどうか迷います。

急いでることではなくて、考えはじめた方がいいと思います。もしかしたら次のユーザミーティングの時、発表・話すればいいかもしれません。

**Comment by aminophen** [comment]
私も kmaeda さんと同じ意見です。

私も一人の Mac ユーザでして、tltexjp をインストールするのは面倒だと思います。ただ、今後 TeX Live の標準インストールよりも優れた「日本人向け TeX installer」が完成すれば、そのときは TeX Live からは除外してもらって installer 側で助けてあげればよいと思います。たとえば小川さんの [UpTeX.app](http://www2.kumagaku.ac.jp/teacher/herogw/) には最初から jfontmaps-nonfree を bundle してもらう、という方法ができそうですね。

**Comment by norbusan** [comment]
同じ問題はこれからckfontmapsに発生する予想ですよね。
Karlさんはいつかダメ言うかもしれませんから、これからどうしましょうか？
ckfontsmapsをそのまま入れてみればいいと思いますが、将来いつかsplitしないといけない可能性があります。

**Comment by aminophen** [comment]
> 同じ問題はこれからckfontmapsに発生する予想ですよね。

おっしゃるとおりです。いま split するほうがよいでしょうか。texjporg/ckfontmaps のうち free なのは noEmbed, baekmuk (ko), unfonts (ko), arphic (sc/tc), solaris (ko) です。

**Comment by norbusan** [comment]
逆に、ckfontmapにsplitされたとしたら、もしかしたら、jfontmapsもsplitしないといけない。。。
迷います。
一応Karlさんと相談しようと思います。

**Comment by aminophen** [comment]
よろしくお願いします。特に jfontmaps のヒラギノは、日本の Mac ユーザがほとんど全員使っていますので、突然消えると大混乱になります。

**Comment by norbusan** [comment]
他のアイディアがあった：新しいcjk-fontmapsを作れて、今のjfontmapsとckfontmapsを合わせて、全部アップすればどうでしょうか？freeなフォントがいろいろが入ってるから、分離しなくていいかもしれません。。。

**Comment by aminophen** [comment]
> freeなフォントがいろいろが入ってるから、分離しなくていいかもしれません。。。

jfontmaps の free は、いまは ipa, ipaex だけですね。ほかにも新しく作りましょうか。そしたら free の割合が増えます。（もしそうするなら、font files も TeX Live に入れますか？）

**Comment by norbusan** [comment]
大賛成！！！
でも、jfontmaps + ckfontmapsの合わせは別の話です。どう思いますか？

**Comment by aminophen** [comment]
> jfontmaps + ckfontmaps

devel ML で提案したような、kanji-config-updmap に --sc / --tc / --ko / --jp というオプションを追加する案を使うなら、maps も合わせたほうが楽です。

名前は cjk-fontmaps に変えず、jfontmaps のままでも良いのではないでしょうか。名前が変わるのは好きではないです。また、cjk という名前が付くと CJK.sty のパッケージと間違われそうなので、j のままにして collection-langjapanese へ入るようにしたいです。

**Comment by norbusan** [comment]
むむむむ、よくないと思います：c-langjapaneseはだめです。KとCに対応すれば、それぞれのcollectionにいれ、またc-langcjkにいれば一番いいです。

TeX Liveならば、名前の変更は問題がありません。collection-langjapaneseをインストールされた場合は自動に新しいパッケージもインストールされています。

CJKとの間違えか。。。ないと思いますけれども。。。

もう少し考えましょう。Karlとの相談もします。

**Comment by aminophen** [comment]
たしかに K と C のフォントを使いますが、upLaTeX と japanese-otf でインストールする TFM / VF から TTF / OTF への mapping をするだけなので、c-langjapanese に入った方がよいと思っています。upLaTeX が無いと、maps はまったく使えません。

何か私が勘違いしているかもしれませんし、Karl さんと相談していただいたほうがよいですね。

**Comment by aminophen** [comment]
何か私が勘違いしているかもしれませんし、Karl さんと相談していただいたほうがよいですね。

**Comment by norbusan** [comment]
On Mon, 05 Dec 2016, Hironobu Yamashita wrote:
> たしかに K と C のフォントを使いますが、upLaTeX と japanese-otf でインストールする TFM / VF から TTF/OTF への mapping をするだけなので、c-langjapanese に入った方がよいと思っています。upLaTeX が無いと、maps はまったく使えません。

なるほど。。。考えています。。。

Norbert

**Comment by aminophen** [comment]
フリーの日本語フォント moga-mobo を追加しました。

**Comment by aminophen** [comment]
停滞していますが、そろそろ中国語・韓国語の map を TeX Live に入れたいので動こうと思います。

- ckfontmaps の成果物を jfontmaps にすべて merge します。
- jfontmaps は今のまま（nonfree も入れた状態）で、中国語・韓国語は free だけにします。
- kanji-config-updmap を中国語・韓国語に対応させます。

merge にあたり、jfontmaps という名前でよいでしょうか。それとも、新しい名前、たとえば ptex-fontmaps というのはどうでしょうか？ これなら collection-langjapanese の ptex/uptex と一緒に入れてもらえると思います。 → #7 として Pull request します。

**Comment by aminophen** [comment]
merge にあたり、jfontmaps という名前でよいでしょうか。それとも、新しい名前、たとえば ptex-fontmaps というのはどうでしょうか？ これなら collection-langjapanese の ptex/uptex と一緒に入れてもらえると思います。

**Comment by norbusan** [comment]
了解です。Karlさんのオケーをもらいました。明日全部確認します。

**Comment by aminophen** [comment]
Karl さんから ok をもらえたとのこと、安心しました。ありがとうございます。

**Comment by norbusan** [comment]
hmmm、今読んで、ちょっと疑問があります：JとCKのフォントを別の方法するのはあまり好きじゃありません。
とりあえずfree/nonfree splitしなくて、そのまま全部入れた方がいいと思います。そうじゃなかったら、「なぜ」と言われてると思います。どうですか？

**Comment by aminophen** [comment]
free fonts は少ないですし、今後増えることも少ないです。理由は、特に CJK fonts は Latin fonts より文字が多く、volunteer で作るには大変だからです。

それに対し、nonfree fonts は、今でも追加したければたくさん追加できます。しかも、追加したくなくても追加しないといけないことがあります。たとえば、Mac では hiragino から hiragino-elcapitan に変わって、Win では yu-win → yuwin10 に変わって増えました。もしかしたら hiragino-sierra とか yu-win11 とか、OS が新しくなったら全部作らないといけないかもしれません。

だから、upper limit を決めたいです。私は今まで入っていた nonfree fonts は remove したくないです。でも、TeX Live が nonfree をあまり好きじゃないこともわかります。だから、これ以上 nonfree fonts を増やさないための提案です。

**Comment by aminophen** [comment]
Karl さんの ok が「今まで入っていた nonfree は許す」という意味なら、CK は分けるという提案になりますし、将来できるだけ J も nonfree を増やさない方がよいです。もし、Karl さんの ok が「将来たくさん nonfree を増やしてよい」という意味なら、CK も split はしなくてよいです。

**Comment by norbusan** [comment]
またKarlさんに連絡しました。見てみましょう。

**Comment by norbusan** [comment]
Karlさんも僕の考えとおり、すべてのCJKを同法にした方がいいと言いました。ですから、とりあえず全部そのままに入れましょう。
これでこのissueもcloseします。

**Comment by aminophen** [comment]
nonfree が増えることも問題ない、ということですね。ありがとうございます。
