### ISSUE TITLE
Noto / SourceHan セット追加

### ISSUE THREAD

**Issue by aminophen** [texjporg/jfontmaps#10]
TeX Live 2017 の dvipdfmx が Noto Serif/Sans あるいは SourceHanSerif/Sans を利用可能になっていることは，すでに http://qiita.com/zr_tex8r/items/9dfeafecca2d091abd02 などで書かれている通りです。Debian のパッケージなどでも Noto OTC が提供されており，「kanji-config-updmap を使ってデフォルトに使いたい」という要望を受けています。

しかし，現時点ではこれを採用していません。理由は upLaTeX + dvipdfmx 専用であることで，

- pLaTeX では使えない
- OTF パッケージの cid-ナントカ は使えない
- dvips では使えない

ということです。updmap は「全部のフォントを一度に変更する」ためのプログラムなので，upLaTeX + dvipdfmx だけ変更するという作業は updmap のコンセプトに反します。

とはいえ，Noto / SourceHan を使えないのはあまり嬉しくないわけで，どこかの仕様を拡張する余地はないか，と考えています。

- **kanji-config-updmap は最初に ptex-プリセット名.map の存在チェックをして，** 存在すればその プリセット名 のマップを updmap が管理する kanjix.map などに反映させる。

例えばこの太字部分でも引っかかるはずですが，例外処理で「使えるスキームだけ」設定することができないか，お知恵を貸してください。

**Comment by norbusan** [comment]
提案：
＊updmapにxxEmbedだけじゃなくて、xxEmbed.pkg対応する
＊pkgはotf, otf-up, ptex, uptexである
＊xxEmbed.pkgは設定されていない場合は、xxEmbedが使われてる

**Comment by aminophen** [comment]
ノルベルトさん，ご提案ありございます。

なるほど。xxEmbed.pkg の仕組みがあれば対応できそうです。updmap.pl の拡張も必要なので，ゆっくり考えて，時間のあるときに実装してみましょう。

**Comment by norbusan** [comment]
updmapの更新の準備しました：
https://git.preining.info/texlive.git/commit/?h=embed-sub&id=4caffc722eee13cef4e57b2629d0ec7940a68ccf

updmap.cfgにたとえば

`jaEmbed.uptex hiragino`

入れれば、下記のとおりになります

````
[~] updmap-sys 
...
  jaEmbed replacement string       : ipaex (/home/norbert/tl/2017/texmf-dist/web2c/updmap.cfg)
  jaEmbed.uptex replacement string : hiragino (/home/norbert/tl/2017/texmf-dist/web2c/updmap.cfg)
  jaVariant replacement string     : <empty> (default)
...
````

`kanjix.map`は正しく更新されました。

Notoの例のuptex-notoなど僕に送れば、確認します。

どう思いますか？

**Comment by aminophen** [comment]
ありがとうございます。まだ noto のマップをどう書くのが一番良いか考えている途中なので，例を送ることはできませんが，とりあえず updmap.pl の方を読んでコードを理解しようとしています。

まず，updmap.pl で ko, sc, tc が「otf otf-up」となっていますが，

~~~~
  ja => [ qw/ptex otf uptex otf-up/ ],
  ko => [ qw/otf uptex/ ],
  sc => [ qw/otf uptex/ ],
  tc => [ qw/otf uptex/ ]
~~~~

が正しいと思います。ptex-fontmaps のマップを見ていただくとわかると思います。

**Comment by norbusan** [comment]
了解、更新しましたけど、otfとuptexは大丈夫ならば、なんでotf+uptex = otf-upじゃないとわかりません。

**Comment by norbusan** [comment]
pxchfonの「dumpmaptl」オプジョンを使って、*-noto.mapを作成しました。これで簡単なドキュメントはうまくpdfに変化出来ました。



[otf-noto.map.txt](https://github.com/texjporg/jfontmaps/files/1103788/otf-noto.map.txt)
[otf-up-noto.map.txt](https://github.com/texjporg/jfontmaps/files/1103789/otf-up-noto.map.txt)
[ptex-noto.map.txt](https://github.com/texjporg/jfontmaps/files/1103790/ptex-noto.map.txt)
[uptex-noto.map.txt](https://github.com/texjporg/jfontmaps/files/1103791/uptex-noto.map.txt)

**Comment by aminophen** [comment]
> pxchfon の「dumpmaptl」オプション

私もほとんどはそれで ok だと思っていますが，一部問題があると思っています。たとえば otf-noto.map の  cid-* は Noto の .ttc では絶対に動かないので，これは削除した方が良いと思っています。ptex-noto.map も作ることはできますが，pLaTeX は Unicode に対応していないため，noto を使うことができません。なので，どのマップを実際に ptex-fontmaps で配るかは考えないといけません。

**Comment by aminophen** [comment]
> otfとuptexは大丈夫ならば、なんでotf+uptex = otf-upじゃないとわかりません。

例えば

- ptex-hiragino.map は pTeX standard fonts の日本語 TFM フォントの名前
- uptex-hiragino.map は upTeX standard fonts の日本語 TFM フォントの名前
- otf-hiragino.map は japanese-otf の日本語 TFM フォントの名前
- otf-up-hiragino.map は japanese-otf-uptex の日本語 TFM フォントの名前

です。日本語 TFM フォントの名前は，japanese-otf から japanese-otf-uptex になった時に変わっています。しかし，中国語と韓国語の名前は変わっていません。だから，japanese-otf の中国韓国語 TFM フォントの名前は，ptex でも uptex でも otf-{sc,tc,ko}-ms.map なのです。

**Comment by aminophen** [comment]
（コメントが間違っていたので訂正）

> otfとuptexは大丈夫ならば、なんでotf+uptex = otf-upじゃないとわかりません。

例えば日本語マップは

- ptex-ms.map は pTeX standard fonts の日本語 TFM の名前
- uptex-ms.map は upTeX standard fonts の日本語 TFM の名前
- otf-ms.map は **japanese-otf standard fonts の日本語 TFM の名前** ＋ \UTF 用 ＋ \CID 用
- otf-up-ms.map は **japanese-otf-uptex standard fonts の日本語 TFM の名前**

です。このように，**standard fonts の日本語 TFM の名前** は，ptex (japanese-otf) から uptex (japanese-otf-uptex) になった時に変わっています。

しかし，中国語と韓国語マップは，japanese-otf(-uptex) に standard fonts がありません。

- uptex-{sc,tc,ko}-ms.map は upTeX standard fonts の日本語 TFM の名前
- otf-{sc,tc,ko}-ms.map は \UTF 用 ＋ \CID 用

だから，japanese-otf の中国韓国語 TFM フォントの名前は，up-otf が要らないのです。

**Comment by norbusan** [comment]
説明をありがとうございますが、まだ不明点があります。自分の解釈を書きますが、間違ったら教えてください。

- 質問１：日本語だけの話で、otf-up-*はCIDとUTFがないから、notoに対応していないということですよね？japanese-otf(-uptex) standard fontsは対応していないですが、CID/UTFで対応になります。

- 質問２：{sc,tc,ko}の話：そこでNotoの対応は、別のmapを作成しないといけないですよね。

上のとおりならば、下記のmapがあれば正しいですか：
uptex-noto-otc, otf-noto-otc, uptex-{sc,tc,ko}-noto-otc, otf-{sc,tc,ko}-noto-otc

(noto-otcはpxchfonと同じ名前にしようと思ってるので！）

アップしたuptex-notoとotf-notoを使って、{sc,tc,ko}のファイルも作成してから、いれればいいですか？

よろしくお願いします。

ノルベルト

**Comment by aminophen** [comment]
> 日本語だけの話で、otf-up-*はCIDとUTFがないから、notoに対応していないということですよね？

いえ，noto は \UTF を使うことができます。しかし，\CID を使うことができません。理由は，noto というフォントが Adobe-Japan1 に従っていなくて，代わりに Adobe-Identity0 という特別な CMap を持っているからです。[この記事](http://d.hatena.ne.jp/zrbabbler/20170617/1497682168)で「AJ1 でない OpenType フォント」と書かれていますが，これは noto が Adobe-Identity0 であることを意味します。

だから，ptex-fontmaps でどんな作業をしても，日本語の \CID は使うことができません。pxchfon の dumpmaptl では，cid で始まる lines がありますが，これは「間違っている」，あるいは「まだ experimental feature なので対応していない」のだと思います。

同じように

\usepackage[multi]{otf}

で中国語の \CIDC, \CIDT, 韓国語の \CIDK という命令が定義されますが，これも noto では使うことができません（Adobe-GB1, Adobe-CNS1, Adobe-Korea1 の CMap を使わずに，全部 Adobe-Identity0 だから）。だから，otf-up-{sc,tc,ko}-noto.map は cid で始まる lines を書いてはいけません。

ところで，\usepackage[noto]{pxchfon} でエラーが出るのは pxchfon のバグです。 → zr-tex8r/PXchfon#5 結局，私たちは 4 つの maps を作らないといけません。

- noto
- noto-otc
- sourcehan
- sourcehan-otc

**Comment by aminophen** [comment]
ところで，\usepackage[noto]{pxchfon} でエラーが出るのは pxchfon のバグです。 → zr-tex8r/PXchfon#5 結局，私たちは 4 つの maps を作らないといけません。

- noto
- noto-otc
- sourcehansan
- sourcehansan-otc

**Comment by aminophen** [comment]
> {sc,tc,ko}の話：そこでNotoの対応は、別のmapを作成しないといけないですよね。

これはその通りですね。pxchfon は中国語・韓国語の noto(-otc) のセットを用意していません。私たちで新しく作らないといけません。

**Comment by aminophen** [comment]
noto-otc の maps を作るスクリプトを試しに作ってみました。

https://gist.github.com/aminophen/169d9d4083bbd47efc718cacd42df57b

\usepackage[dumpmaptl,noto-otc]{pxchfon} より行が少ないですが，必ず正しく動くのはこれだけなのではないかと思います。まだテストが十分でないので，テストケースも私の所で作ってみます。

**Comment by aminophen** [comment]
https://git.preining.info/texlive.git/commit/?h=embed-sub&id=c48b6daf172bbb1d9106f050d256e5396e88c842

を試してみると，期待どおりに動きました。ありがとうございます！

まだ maps のテストが十分ではないので，最初に noto-otc だけ書いてみました。テスト用の .tex ファイルはまた明日か明後日に書きます。

**Comment by norbusan** [comment]
ありがとうございます。全部masterに入れてよかったです。
僕はこれからkanji-config-updmap.plを対応できるように更新します。
noto-otcの場合は、jaEmbed.uptexなどを使うことにします。

**Comment by aminophen** [comment]
noto などの「Adobe-Identity0 なフォント」で正常に動作しないことを一覧にしておきます。

- otf パッケージの `\CID` シリーズおよび ajmacros（`\ajナントカ` 命令など）の大半の命令。
- otf パッケージ使用時の「クオート」、つまり `“` や `”` など。
    - これらは otf パッケージが「自動的に縦・横でグリフを切り替える」ために Adobe-Japan1 のマップを使っているため、横書きでも縦書きでも文字化けが生じる。

この2点目はあまり自明ではないので、見落としてしまうケースが出てきそうです。他にも otf パッケージが持っている機能が逆に文字化けにつながるかもしれないので、いろいろテストした方が良さそうです。

なお、上に書いたふたつとも、pxchfon では「余分なマップ行がある」ので、エラーが出ずにそのまま文字化けした PDF ができてしまいますが、ptex-fontmaps では「余分な行を全て消した」ので、dvipdfmx 実行中に「フォントがマップされていない」というエラーが出て止まるようになるはずです。

**Comment by aminophen** [comment]
メモ：

- http://scientre.hateblo.jp/entry/20160208/tex_genshin

に，Noto / SourceHan を有志が TTF に変換した(別名だけどグリフは同じ)フォントたちへのリンク情報があります。Adobe-Identity0 ではないはずなので，updmap.pl の拡張をせずに綺麗な出力を得ることができると思うので，これも Noto / SourceHan とは別にプリセットしたいですがどうでしょう？

→ #23 で原ノ味フォントを使えるようになるので，TTF 版追加はとりやめ。
