### ISSUE TITLE
hiragino / hiragino-pronでヒラギノ明朝W2が不足する

### ISSUE THREAD

**Issue by squeuei** [texjporg/jfontmaps#18]
hiragino-elcapitanでは`hminl-h`、`hminl-v`がヒラギノ明朝Pro/ProN W2からW3へと置き換えられています。

https://github.com/texjporg/jfontmaps/commit/9af223b089d353be2a873838cbcde90db63d3b2c

一方、hiragino / hiragino-pronでは従来どおりW2が使用されています。
しかしながら、ヒラギノフォントのパッケージ製品であるヒラギノ基本6書体パックにヒラギノ明朝Pro/ProN W2は含まれていません。
また、これらの書体はREADMEにて記載されているOS X ～Yosemiteや一太郎2012 プレミアム/スーパープレミアムにも含まれていません。

> 	bundled with Mac OS X 10.5--10.10,
> 	or Japanese word processor Ichitaro 2012 Premium/Super-premium editions

hiragino / hiragino-pronにhiragino-elcapitanと同様の変更が加えられなかったことには、何らかの理由、経緯があるのでしょうか。

**Comment by aminophen** [comment]
hiragino-elcapitan や hiragino-highsierra は，macOS のバージョン名が入っている通り，「macOS にバンドルされているフォントを使うために作られたもの」です。W2 を外して W3 に変えた理由は，このことから自ずとお分りいただけるでしょう。

これに対し，hiragino は macOS の名前がついていないので，私は「商用のヒラギノを購入する人向け」と解釈しています。W2 以外については“たまたま” macOS や一太郎にバンドルされている，とお考え頂けないでしょうか。

**Comment by squeuei** [comment]
READMEの記述が「macOSや一太郎を持っている人向けのmapである」を意味しない旨、承知いたしました。
ローカルの環境にてotfのシンボリックリンクで対応しようと思います。
ご回答いただきありがとうございました。
