### ISSUE TITLE
kanji-config-updmapで存在しないフォント用のmap生成

### ISSUE THREAD

**Issue by kbhonda** [texjporg/jfontmaps#20]
例えば，morisawaフォントがない環境で
````sh
kanji-config-updmap-sys morisawa
````
はエラーになります．
ただ，これをエラーにしないで
mapの設定だけ行うオプションがあれば助かります．
````sh
kanji-config-updmap-sys --force morisawa
````
とかすると，morisawaフォントが存在しなくても
````sh
kanji-config-updmap-sys morisawa
````
と同じ動作をしてくれるということです．

事情としては，以下のような感じです．

dockerでTeXLiveのイメージ作成の際にdockerfile内で
kanji-config-updmap-sysを実行させたいのですが，
ホストにあるフォントを使いたくても
イメージ作成の際にはホストへのマウントはできませんので，
上述のようにエラーになります．
もちろん，フォントそのものをイメージの中にコピーすればいいのですが，
ライセンス的にグレーなものがあるのでコピーは避けたいのです．
（ホストのフォントフォルダをマウントしてコンテナ内にはいって
kanji-config-updmap-sysしてからイメージに書き出せばいいですし，
実際，そうやって作ったイメージを使ってますが，
dockerfileだけで作れればよいと思います）

**Comment by norbusan** [comment]
了解です。GWの後この機能を追加します。

**Comment by aminophen** [comment]
‪kanji-config-updmap(-sys) はフォントファイルとマップファイルの存在を確認してから，裏で updmap(-sys) を実行しているだけなので，updmap(-sys) を直接叩けば存在チェックなしにマップの設定だけを行えると思います。‬

‪うろ覚えですが，‬

‪updmap-sys --setoption jaEmbed morisawa‬

‪で kanji-config-updmap-sys morisawa と同じマップ設定を行えると思います。‬

‪とはいえ，確かに kanji-config-updmap(-sys) で実行できるようにするのも名案だと思うので，検討してみます。‬

**Comment by kbhonda** [comment]
norbusanさん，aminophenさん

ありがとうございました．よろしくお願いします．

>‪updmap-sys --setoption jaEmbed morisawa‬

そうでした．kanji-config-updmap-sysにしか思いついてませんでした．
これで思っていたものはできたので，なんとかなります．
ありがとうございました．

**Comment by munepi** [comment]
@kbhonda 
もっというと、 `$TEXMF/web2c/updmap.cfg` （`$TEXMF` は、通常、system wideの `TEXMFLOCAL` か user-per wideの `TEXMFHOME` ）を自前で制御していると、設定ファイルベースで完全にフォント環境を管理できますね。あとは、 `updmap.cfg` を用意していると、 `updmap-sys` を実行するだけで、マップファイルが全部再生性されますから。

`$TEXMF/web2c/updmap.cfg` の `jaEmbed` （従来の `kanjiEmbed` で ja, sc, tc, ko 全部まとめてでもOK）を自前で 

```
jaEmbed <family>
```

を書くだけですね。
また、（主に商業用な）和文フォントと合わせて、（商業用な）欧文フォントも一括で `updmap.cfg` に登録しています。

**Comment by kbhonda** [comment]
munepiさん

アドヴァイスありがとうございます．
それいいですね．
dockerfileの中にupdmap.cfgを生成するようコードいれて
updmap-sysを動かせばnomkmapオプションとかあんまり考えないで
一回ですみますね
これから欧文関係一式を整理する予定ですので
試させていただきます．

**Comment by norbusan** [comment]
@aminophen フォントファイルなくても、updmapはちゃんと動くと思います：例えば、僕は「moga-mobu」のファイルを持っていないのに、jaEmbedにmoga-mobuを書くと、updmap-sysが動きます：
```
[~] updmap-sys 
updmap will read the following updmap.cfg files (in precedence order):
  /usr/local/share/texmf/web2c/updmap.cfg
  /home/norbert/tl/2019/texmf-dist/web2c/updmap.cfg
updmap may write changes to the following updmap.cfg file:
  /home/norbert/tl/2019/texmf-config/web2c/updmap.cfg
dvips output dir: "/home/norbert/tl/2019/texmf-var/fonts/map/dvips/updmap"
pdftex output dir: "/home/norbert/tl/2019/texmf-var/fonts/map/pdftex/updmap"
dvipdfmx output dir: "/home/norbert/tl/2019/texmf-var/fonts/map/dvipdfmx/updmap"

updmap is creating new map files
using the following configuration:
  LW35 font names                  : URWkb (/home/norbert/tl/2019/texmf-dist/web2c/updmap.cfg)
  prefer outlines                  : true (/home/norbert/tl/2019/texmf-dist/web2c/updmap.cfg)
  texhash enabled                  : true
  download standard fonts (dvips)  : true (/home/norbert/tl/2019/texmf-dist/web2c/updmap.cfg)
  download standard fonts (pdftex) : true (/home/norbert/tl/2019/texmf-dist/web2c/updmap.cfg)
  jaEmbed replacement string       : moga-mobo (/usr/local/share/texmf/web2c/updmap.cfg)
  jaVariant replacement string     : <empty> (/usr/local/share/texmf/web2c/updmap.cfg)
  scEmbed replacement string       : arphic (/home/norbert/tl/2019/texmf-dist/web2c/updmap.cfg)
  tcEmbed replacement string       : arphic (/home/norbert/tl/2019/texmf-dist/web2c/updmap.cfg)
  koEmbed replacement string       : baekmuk (/home/norbert/tl/2019/texmf-dist/web2c/updmap.cfg)
  create a mapfile for pxdvi       : false (default)

Scanning for LW35 support files  [  3 files]
Scanning for MixedMap entries    [ 44 files]
Scanning for KanjiMap entries    [ 11 files]
Scanning for Map entries         [338 files]

Generating output for dvipdfmx...
Generating output for ps2pk...
Generating output for dvips...
Generating output for pdftex...

Files generated:
  /home/norbert/tl/2019/texmf-var/fonts/map/dvips/updmap:
       15792 2019-05-06 17:15:12 builtin35.map
       21265 2019-05-06 17:15:12 download35.map
     3166951 2019-05-06 17:15:12 psfonts_pk.map
     3427846 2019-05-06 17:15:12 psfonts_t1.map
     3421349 2019-05-06 17:15:12 ps2pk.map
          14 2019-05-06 17:15:12 psfonts.map -> psfonts_t1.map
  /home/norbert/tl/2019/texmf-var/fonts/map/pdftex/updmap:
     3421356 2019-05-06 17:15:12 pdftex_dl14.map
     3419691 2019-05-06 17:15:12 pdftex_ndl14.map
          15 2019-05-06 17:15:12 pdftex.map -> pdftex_dl14.map
  /home/norbert/tl/2019/texmf-var/fonts/map/dvipdfmx/updmap:
        9613 2019-05-06 17:15:11 kanjix.map

Transcript written on "/home/norbert/tl/2019/texmf-var/web2c/updmap.log".
updmap: Updating ls-R files.
```

ですから、「`--force`」を追加して、フォントファイルの存在の確認しない機能にしようと思います。

**Comment by norbusan** [comment]
PRを送りました： https://github.com/texjporg/jfontmaps/pull/21
どう思いますか？

**Comment by aminophen** [comment]
#21 で良いと思います。マージしました。

**Comment by aminophen** [comment]
20190506.0 としてリリースし，CTAN にアップロードしておきます。

**Comment by norbusan** [comment]
ありがとうございます。
