### ISSUE TITLE
次回リリース準備（CK 多ウェイト）

### ISSUE THREAD

**Issue by aminophen** [texjporg/jfontmaps#29]
#28 より。

----

あと、本件とは関係ありませんが、
次回 ptex-fontmaps をリリースされる際には、Windows で 2004-{H|V} を tlgs に入れる ptex-fontmaps-tlpost.pl
https://gist.github.com/trueroad/d5468b8d0f93e8082c20c59964792a90
も、よろしくお願いいたします。

----

それから，cjk-gs-integrate の haranoaji データベースのエイリアスも要検討。

また，このリポジトリの名前をそろそろ jfontmaps → ptex-fontmaps に変えたいのですが，管理者権限をお持ちの方はいらっしゃいますか？

**Comment by munepi** [comment]
> また，このリポジトリの名前をそろそろ jfontmaps → ptex-fontmaps に変えたいのですが，管理者権限をお持ちの方はいらっしゃいますか？

今の段階ですぐに `jfontmaps → ptex-fontmaps` に変えてしまってもよいでしょうか？

**Comment by aminophen** [comment]
かまいません。私も自分のリポジトリをリネームしたことがありますが，リダイレクトしてくれますし。CTAN へは次のリリース時（年内）に知らせます。

**Comment by munepi** [comment]
@aminophen https://github.com/texjporg/ptex-fontmaps/ 
`jfontmaps → ptex-fontmaps` へrename完了しました。

**Comment by aminophen** [comment]
@munepi ありがとうございます。README などはこちらで修正します。

**Comment by aminophen** [comment]
> cjk-gs-integrate の haranoaji データベースのエイリアス

とりあえず https://github.com/texjporg/cjk-gs-support/commit/0317845e3dd7c65021d9971fa64d0d92f810e6dc で付けてみました。この機能はスクリプトが「システムに存在するフォントから自動で決定する」というものなので，環境によって実際に使われるフォントが異なるのは当たり前ですし，番号は適当に45にしておきました。

**Comment by aminophen** [comment]
20201227.0 としてリリースしました。

> ptex-fontmaps-tlpost.pl

https://www.tug.org/svn/texlive?view=revision&revision=57238 で追加しました。
