### ISSUE TITLE
Add --user option for updmap call

### ISSUE THREAD

**Issue by aminophen** [texjporg/jfontmaps#9]
[TeX Live r43793](http://www.tug.org/svn/texlive?view=revision&revision=43793) で，updmap --sys または updmap --user のどちらかのオプションが必須になりました。したがって kanji-config-updmap にも 8d2d784 で追加しました。これがないとスクリプトが user mode でエラーになるはずです。

~~ノルベルトさんが ok をくれたらリリースします。~~ → edit: kanji-config-updmap-user を追加して，raw script はエラーにしたほうが良いかもしれないので，次のコメントを追加しました

**Comment by aminophen** [comment]
TeX Live には updmap-user と updmap-sys がありますので，kanji-config-updmap-user と kanji-config-updmap-sys にしたほうが consistent になると私は思うのですが，皆さまはどう思いますか？

**Comment by norbusan** [comment]
ちょっと待ってください。-userがない場合も対応したいと思います。

**Comment by norbusan** [comment]
ちょっと待ってください。-userがない場合も対応したいと思います。

**Comment by norbusan** [comment]
-user/-sysモード
updmapのバーシオンを確認コード
などの変更しました。
余裕があれば、余裕があれば、是非確認をお願いします。
ノルベルト

**Comment by aminophen** [comment]
> -user/-sysモード
> updmapのバーシオンを確認コード
 > などの変更しました。

ノルベルトさん、ありがとうございます。正しく動きました。

p.s. BachoTeX、楽しんでいらしてください。

**Comment by norbusan** [comment]
確認をありがとうございます。BachoTeXはいつものとおり面白いですよ。来年山下さんもう来れば？

**Comment by aminophen** [comment]
行ってみたいです。会社の休みがとれれば，ぜひ。

**Comment by aminophen** [comment]
> Plan for TeX Live 2017:
> 8may: final updates from CTAN, final doc tweaks.

なので，早めに今日 release しました。

**Comment by norbusan** [comment]
了解です。ありがとうございます。
